<a href="https://colab.research.google.com/github/Soyabali/BareCodeReader-hanywell/blob/master/indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
import torch

Indexing

In [8]:
tensor = torch.tensor([
                       [10,20,30],
                       [40, 50, 60],
                       [70, 80, 90]])
print(tensor.ndim)
print(tensor.shape)

2
torch.Size([3, 3])


In [11]:
# Access first row
tensor[0]

tensor([70, 80, 90])

In [15]:
# Access first column
tensor[:,0]

tensor([10, 40, 70])

In [18]:
# First Twor rows
print("First two rows : \n",tensor[:2])


First two rows : 
 tensor([[10, 20, 30],
        [40, 50, 60]])


In [19]:
# Middle elements (row 1, column 1 and 2 only)
print(tensor[1,1:3])

tensor([50, 60])


In [20]:
# Fancy indexing
# (0,1)---> 20
# (2,2) ---> 90

selected_elements = tensor[[0,2],[1,2]]
print(selected_elements)

tensor([20, 90])


In [21]:
# boolean indexing
mask = tensor>50
print(mask)
print(tensor[mask])


tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])
tensor([60, 70, 80, 90])


In [24]:
# Changingtensor values via indexing
print(tensor)
tensor[0,1]=25
print(tensor)
tensor[0,0]=786
print(tensor)


tensor([[10, 25, 30],
        [40, 50, 60],
        [70, 80, 90]])
tensor([[10, 25, 30],
        [40, 50, 60],
        [70, 80, 90]])
tensor([[786,  25,  30],
        [ 40,  50,  60],
        [ 70,  80,  90]])


In [25]:
tensor[:,0] = torch.tensor([100,200,300])
print(tensor)

tensor([[100,  25,  30],
        [200,  50,  60],
        [300,  80,  90]])


In [26]:
indices = torch.tensor([0,2])
selected_rows = torch.index_select(tensor,dim=1,index=indices)
print(selected_rows)

tensor([[100,  30],
        [200,  60],
        [300,  90]])


In [27]:
print(tensor[:,::2])

tensor([[100,  30],
        [200,  60],
        [300,  90]])


In [28]:
torch.flip(tensor,dims=(0,))

tensor([[300,  80,  90],
        [200,  50,  60],
        [100,  25,  30]])